services:
  - type: web
    name: my-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: my-portfolio-6szg.onrender.com
      - key: DJANGO_SECRET_KEY
        value: your-production-secret-key
      - key: DJANGO_DEBUG
        value: "False"
